#!/usr/bin/env bash
# Modify /etc/hosts file to update localhost and facebook.com resolutions
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts

# Flush DNS cache
sudo systemd-resolve --flush-caches
